version: '2'
services:

  db:
    build: db
    image: pleroma/db
    restart: always
    volumes:
      - ./db/postgres:/var/lib/postgresql/data

  web:
    build: web
    image: pleroma/pleroma
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./web/uploads:/pleroma/uploads
